"""Extract Galaga's enemy movement data from the user's own ROM set.

    python3 extract.py path/to/galaga.zip build

Writes (all derived from the ROM, so none of it belongs in the repository):
  motion_data.s  the flight scripts and wave tables as assembler source for
                 the Amiga port; script jumps become big-endian offsets from
                 MotionScripts
  paths.txt      the same data decoded for reading
  paths.png      the 24 entry paths as flown by the reference stepper
                 (needs pillow; skipped without it)
"""

import sys
from pathlib import Path

import bombs as B
import dives as D
import galaga_motion as G


def all_scripts(rom: G.Rom) -> tuple[dict[int, tuple], dict[int, str]]:
    """Every script token reachable from a known entry point, and entry labels."""
    labels = {a: f"Entry{i:02d}" for i, (a, _) in reversed(list(enumerate(rom.entry_paths())))}
    labels.update({a: "".join(w.capitalize() for w in n.split("_")) for a, n in G.DIVES.items()})
    for i in range(3):
        labels.setdefault(rom.word(rom.main, G.ESCORT_TABLE + 2 * i), f"Escort{i}")
    tokens: dict[int, tuple] = {}
    for a in labels:
        tokens.update(G.parse_script(rom, a))
    return dict(sorted(tokens.items())), labels


def token_bytes(rom: G.Rom, addr: int, tok: tuple) -> int:
    if tok[0] == "step":
        return 3
    code = next(k for k, v in G.NAMES.items() if v == tok[0])
    return 1 + G.ARG_BYTES.get(code, 0)


def script_offsets(rom: G.Rom) -> dict[int, int]:
    """Where each token's ROM address ends up, as an offset from MotionScripts."""
    tokens, _ = all_scripts(rom)
    out, at = {}, 0
    for addr, tok in tokens.items():
        out[addr] = at
        at += token_bytes(rom, addr, tok)
    return out


def describe(tok: tuple) -> str:
    if tok[0] == "step":
        _, hi, lo, turn, n = tok
        speed = f"speed {(hi + lo) / 2:g}" if hi == lo else f"speed {hi}/{lo}"
        return f"{speed} px/frame, turn {turn:+d}, {n} frames"
    if tok[0] in ("aim_at_fighter", "aim_red"):
        return f"{tok[0]}: frames by fighter position {list(tok[1:])}"
    if len(tok) == 2 and tok[0].startswith(("jump", "spawn")):
        return f"{tok[0]} -> {tok[1]:04x}"
    return " ".join(str(t) for t in tok)


def stage_rows(rom: G.Rom, base: int, rows: int) -> list[str]:
    out = []
    for r in range(rows):
        row = rom.main[base + 18 * r : base + 18 * r + 18]
        waves = []
        for w in range(5):
            extra, a, b = row[2 + 3 * w : 5 + 3 * w]
            side = lambda v: f"path {v & 0x3F:2d}{'M' if v & 0x40 else ' '}"  # noqa: E731
            together = "together" if b & 0x80 else "in a line"
            waves.append(f"[{side(a)} + {side(b)} {together}, extras {extra:02x}]")
        out.append(f"  row {r:2d}: bomb timer {row[0]:02x}, bomb bits {row[1]:02x}  " + " ".join(waves))
    return out


def fly(rom: G.Rom, script: int, start: tuple[int, int, int], mirror: bool) -> list[tuple[int, int]]:
    """Positions along an entry path until it turns for home or leaves."""
    s = bytearray(20)
    s[1], s[3], s[5] = start
    s[8], s[9], s[0x0D], s[0x10] = script & 255, script >> 8, 1, 0x30
    s[0x13] = 0x81 if mirror else 0x01
    env = G.Env(obj_state={0x30: 7})
    pts = []
    for frame in range(900):
        env.frame = frame
        if G.step(s, rom, env) == "end" or s[0x13] & 0x40:
            break
        pts.append(G.screen_pos(s))
    return pts


def main() -> None:
    rom = G.Rom(sys.argv[1])
    out = Path(sys.argv[2])
    out.mkdir(parents=True, exist_ok=True)
    tokens, labels = all_scripts(rom)
    targets = {t[1] for t in tokens.values() if len(t) == 2 and t[0].startswith(("jump", "spawn"))}
    name = lambda a: labels.get(a, f"P{a:04x}")  # noqa: E731
    entries, starts = rom.entry_paths(), rom.start_positions()

    asm = [
        "; generated by motion/extract.py from the user's ROM - do not edit, do not commit",
        "; flight scripts: 3-byte steps (speeds, turn, frames) and command tokens >= $ef",
        "MotionScripts:",
    ]
    txt = ["Flight scripts (address: meaning)", ""]
    for addr, tok in tokens.items():
        if addr in labels or addr in targets:
            asm.append(f"{name(addr)}:")
            txt.append(f"{name(addr)}:")
        raw = rom.sub[addr : addr + token_bytes(rom, addr, tok)]
        if len(tok) == 2 and tok[0].startswith(("jump", "spawn")):
            off = f"{name(tok[1])}-MotionScripts"
            asm.append(f"\tdc.b\t${raw[0]:02x},({off})>>8,({off})&255\t; {describe(tok)}")
        else:
            asm.append("\tdc.b\t" + ",".join(f"${b:02x}" for b in raw) + f"\t; {describe(tok)}")
        txt.append(f"  {addr:04x}: {describe(tok)}")
    asm += ["\teven", "", "; 24 entry paths: script offset, start position pair", "EntryPaths:"]
    for i, (a, k) in enumerate(entries):
        asm.append(f"\tdc.w\t{name(a)}-MotionScripts,{k}\t; {i}")
    asm += ["", "; start positions, two per pair (plain, mirrored): y/2, x/2, heading high byte", "StartPos:"]
    asm += ["\tdc.b\t" + ",".join(f"${b:02x}" for b in p) for p in starts]
    asm += ["", "; scripts the game starts directly", "DiveScripts:"]
    asm += [f"\tdc.w\t{name(a)}-MotionScripts\t; {n}" for a, n in G.DIVES.items()]
    asm += ["EscortScripts:"]
    asm += [f"\tdc.w\t{name(rom.word(rom.main, G.ESCORT_TABLE + 2 * i))}-MotionScripts" for i in range(3)]

    def table(label: str, comment: str, data: bytes, width: int) -> None:
        asm.extend(["", f"; {comment}", f"{label}:"])
        for i in range(0, len(data), width):
            asm.append("\tdc.b\t" + ",".join(f"${b:02x}" for b in data[i : i + width]))

    m = rom.main
    table("StageIndex", "per rank (B, C, D, A): combat stage data row offset for 17 stage slots", m[G.STAGE_IDX : G.STAGE_IDX + 68], 17)
    table("ChallengeIndex", "row offset for the 8 challenging stages", m[G.CHALLENGE_IDX : G.CHALLENGE_IDX + 8], 8)
    table("StageData", "combat stages: bomb timer, bomb bits, 5 x (extras, path, path), $ff", m[G.STAGE_DATA : G.STAGE_DATA + 13 * 18], 18)
    table("ChallengeData", "challenging stages, same layout", m[G.CHALLENGE_DATA : G.CHALLENGE_DATA + 8 * 18], 18)
    table("WaveObjects", "object numbers in arrival order: 5 waves of 8", m[G.WAVE_OBJECTS : G.WAVE_OBJECTS + 40], 8)
    table("BreathePatterns", "formation breathing: 4 sets of bit patterns for 10 columns and 6 rows", m[G.BREATHE_PATTERNS : G.BREATHE_PATTERNS + 64], 16)
    for rank in range(4):
        at = rom.word(m, D.STAGE_CONFIG_INDEX + 2 * rank)
        label, note = ("StageConfig", "per rank, 26 stages x 5 bytes: ten settings a stage, a nibble each") if rank == 0 else (f"StageConfig{rank}", f"rank {rank}")
        table(label, note, m[at : at + D.STAGE_CONFIG_SIZE], 5)
    table("BombFlagTable", "bomb flags by stage setting 0 (x4) and enemies left / 10", m[D.BOMB_FLAGS : D.BOMB_FLAGS + 32], 4)
    table("BossReload", "boss dive timer by stage setting 1 (x4) and enemies left / 10", m[D.BOSS_RELOAD : D.BOSS_RELOAD + 13], 4)
    table("ButterflyReload", "butterfly dive timer by stage setting 2 (x3) and how late in the stage", m[D.BUTTERFLY_RELOAD : D.BUTTERFLY_RELOAD + 30], 3)
    table("BeeReload", "bee dive timer by stage setting 3 (x3) and how late in the stage", m[D.BEE_RELOAD : D.BEE_RELOAD + 30], 3)
    table("EntryBombers", "a bit per enemy from object 8 up, first enemy in bit 7: set if it may bomb on its way in", m[B.ENTRY_BOMBERS : B.ENTRY_BOMBERS + 6], 6)
    table("HomeRc", "per object number: row index, column index of its formation slot", rom.sub[G.HOME_RC : G.HOME_RC + 0x60], 16)
    asm.append("\teven")
    (out / "motion_data.s").write_text("\n".join(asm) + "\n")

    txt += ["", "Entry paths (index: script, start position plain / mirrored as y/2, x/2, heading)"]
    for i, (a, k) in enumerate(entries):
        txt.append(f"  {i:2d}: {name(a)} at {a:04x}, start {starts[2 * k]} / {starts[2 * k + 1]}")
    txt += ["", "Combat stage rows (M = mirrored side)"] + stage_rows(rom, G.STAGE_DATA, 13)
    txt += ["", "Challenging stage rows"] + stage_rows(rom, G.CHALLENGE_DATA, 8)
    (out / "paths.txt").write_text("\n".join(txt) + "\n")
    size = sum(token_bytes(rom, a, t) for a, t in tokens.items())
    print(f"{len(tokens)} script tokens, {size} bytes of scripts, {len(labels)} entry points")

    try:
        from PIL import Image, ImageDraw
    except ImportError:
        return
    scale, cols = 1, 6
    cw, ch = 224 * scale + 12, 288 * scale + 12
    img = Image.new("RGB", (cols * cw, 4 * ch), (24, 24, 24))
    draw = ImageDraw.Draw(img)
    for i, (a, k) in enumerate(entries):
        ox, oy = (i % cols) * cw + 6, (i // cols) * ch + 6
        draw.rectangle((ox, oy, ox + 224 * scale, oy + 288 * scale), fill=(0, 0, 0))
        draw.rectangle((ox, oy + 16, ox + 224, oy + 272), outline=(40, 40, 60))
        for mirror, colour in ((False, (255, 200, 0)), (True, (0, 200, 255))):
            pts = fly(rom, a, starts[2 * k + mirror], mirror)
            for x, y in pts:
                if 0 <= x + 8 < 224 and 0 <= y + 8 < 288:
                    img.putpixel((ox + x + 8, oy + y + 8), colour)
        draw.text((ox + 3, oy + 2), str(i), fill=(200, 200, 200))
    img.save(out / "paths.png")


if __name__ == "__main__":
    main()
