"""Test cases for the game's flight stepper, and the check of its report.

    python3 flighttest.py cases galaga.zip build/flight_cases.i   write the cases
    python3 flighttest.py count galaga.zip                        how many there are
    python3 flighttest.py check galaga.zip results fifths         compare a report

A case is one flight: a script, where it starts, which enemy it is, and what
the scripts can ask about the game (where the fighter is, how hard the stage
is). A FLIGHT_TEST build flies each case and reports where it ended and a
hash of every frame on the way; `check` flies the same cases through
motion/pal_scale.py and compares. With 5 fifths per frame that model is
identical to the arcade; with 6 it is the approved PAL timing.
"""

import sys
from dataclasses import dataclass
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[2] / "motion"))
import galaga_motion as G  # noqa: E402
import pal_scale as P  # noqa: E402
from extract import script_offsets  # noqa: E402

FRAME_LIMIT = 1500  # as in src/flighttest.s
HEADER, RECORD = 8, 16
RESULT = {None: 0, "home": 1, "end": 2}
M32 = 0xFFFFFFFF


@dataclass(frozen=True)
class Case:
    name: str
    script: int  # ROM address
    y: int
    x: int
    head: int
    obj: int
    mirror: bool = False
    fighter_x: int = 0x70
    hard: int = 0
    harder: int = 0
    last_stand: int = 0
    boss_killed: int = 0


def cases(rom: G.Rom) -> list[Case]:
    out = []
    entries, starts = rom.entry_paths(), rom.start_positions()
    objects = list(rom.main[G.WAVE_OBJECTS : G.WAVE_OBJECTS + 40])
    for i, (script, k) in enumerate(entries):
        for mirror in (False, True):
            start = starts[2 * k + mirror]
            # every enemy on the first six paths, so every place in the formation is flown to
            for obj in objects if i < 6 else objects[:1]:
                out.append(Case(f"entry {i}", script, *start, obj, mirror))
            for fighter_x in (0x10, 0x70, 0xE0):  # hard stages, and enemies that only fly through
                out.append(Case(f"entry {i}", script, *start, objects[3], mirror, fighter_x, hard=1))
                out.append(Case(f"entry {i}", script, *start, 0x38, mirror, fighter_x))
    env = P.formation_env()
    dives = dict(G.DIVES)
    for i in range(3):
        dives.setdefault(rom.word(rom.main, G.ESCORT_TABLE + 2 * i), f"escort_{i}")
    for script, name in dives.items():
        for obj in (objects[0], objects[9], objects[20], objects[39]):
            row, col = rom.sub[G.HOME_RC + obj : G.HOME_RC + obj + 2]
            y, x = env.home_loc[row + 1], env.home_loc[col + 1] >> 1
            for mirror in (False, True):
                for fighter_x in (0x10, 0x48, 0x70, 0xA1, 0xE0):
                    for harder in (0, 1):
                        out.append(Case(name, script, y, x, 1, obj, mirror, fighter_x, harder, harder))
                out.append(Case(name, script, y, x, 1, obj, mirror, last_stand=1, boss_killed=1))
                out.append(Case(name, script, y, x, 1, obj, mirror, last_stand=1, boss_killed=0))
    return out


def model(case: Case, rom: G.Rom, fifths: int) -> tuple[int, int, int, int, int, int]:
    """(hash, frames, result, y, x, heading) as the FLIGHT_TEST build reports them."""
    env = P.formation_env()
    env.fighter_x = env.fighter_x_hw = case.fighter_x
    parms = bytearray(11)
    parms[8], parms[9] = case.hard, case.harder
    env.stage_parms, env.last_stand, env.boss_killed_task = bytes(parms), case.last_stand, case.boss_killed
    st = P.State(y=case.y << 8, x=case.x << 8, h=case.head << 30 & M32, ptr=case.script, obj=case.obj, mirror=case.mirror)
    h = result = frames = 0
    while not result and frames < FRAME_LIMIT:
        env.frame = frames
        result = RESULT[P.frame(st, rom, env, fifths)]
        frames += 1
        h = ((h << 5 | h >> 27) & M32) ^ (st.y << 16 | st.x)
        h = (h + st.h) & M32
        h = (h & 0xFFFF0000) | ((h + ((st.yo & 0xFF) << 8 | (st.xo & 0xFF))) & 0xFFFF)
        h ^= result
    return h, frames, result, st.y, st.x, st.h


def write_cases(rom: G.Rom, path: str) -> None:
    offsets, env = script_offsets(rom), P.formation_env()
    lines = ["; generated by tools/flighttest.py - built from the user's ROM, do not commit", "TestEnv:"]
    for table in (env.home_x, env.home_loc):
        lines.append("\tdc.b\t" + ",".join(str(b) for b in table.ljust(32, b"\0")))
    lines += ["; script, y, x, heading, object, mirrored, fighter x, hard, harder, last stand, boss killed", "TestCases:"]
    for c in cases(rom):
        fields = (c.y, c.x, c.head, c.obj, int(c.mirror), c.fighter_x, c.hard, c.harder, c.last_stand, c.boss_killed)
        lines.append(f"\tdc.w\t{offsets[c.script]}\n\tdc.b\t" + ",".join(str(v) for v in fields))
    lines += ["\tdc.w\t-1", "\teven"]
    Path(path).write_text("\n".join(lines) + "\n")


def check(rom: G.Rom, path: str, fifths: int) -> bool:
    data = Path(path).read_bytes()
    all_cases = cases(rom)
    word = lambda at, n: int.from_bytes(data[at : at + n], "big")  # noqa: E731
    if len(data) != HEADER + RECORD * len(all_cases):
        print(f"report is {len(data)} bytes, expected {HEADER + RECORD * len(all_cases)}")
        return False
    bad, outcomes = 0, {}
    for i, case in enumerate(all_cases):
        at = HEADER + RECORD * i
        got = (word(at, 4), word(at + 4, 2), word(at + 6, 2), word(at + 8, 2), word(at + 10, 2), word(at + 12, 4))
        want = model(case, rom, fifths)
        outcomes[want[2]] = outcomes.get(want[2], 0) + 1
        if got != want:
            bad += 1
            if bad <= 10:
                print(f"case {i} differs: {case}")
                print("  hash, frames, result, y, x, heading")
                print(f"  model {want[0]:08x} {want[1]:5d} {want[2]} {want[3]:04x} {want[4]:04x} {want[5]:08x}")
                print(f"  amiga {got[0]:08x} {got[1]:5d} {got[2]} {got[3]:04x} {got[4]:04x} {got[5]:08x}")
    steps, frames = word(0, 4), word(4, 4)
    build = "exact build, identical to the arcade" if fifths == 5 else "PAL build, 1.2 arcade frames per frame"
    print(f"flight stepper, {build}")
    print(f"  {len(all_cases) - bad} of {len(all_cases)} flights identical to the model, {steps} frames flown")
    print(f"  outcomes: {outcomes.get(1, 0)} home, {outcomes.get(2, 0)} left, {outcomes.get(0, 0)} cut off at {FRAME_LIMIT} frames")
    lines = frames * 313 / steps
    print(f"  cost: {lines:.2f} raster lines a flight, {12 * lines:.1f} for all 12 (sound interrupt included)")
    return not bad


def main() -> None:
    rom = G.Rom(sys.argv[2])
    if sys.argv[1] == "cases":
        write_cases(rom, sys.argv[3])
    elif sys.argv[1] == "count":
        print(len(cases(rom)))
    elif not check(rom, sys.argv[3], int(sys.argv[4])):
        sys.exit(1)


if __name__ == "__main__":
    main()
