"""Draw the game's name for the title: build/logo.bin and build/logo.i.

    python3 tools/make_logo.py build

AMIGALAGA in block letters of the game's own (nothing here comes from the arcade):
yellow over gold over rust, a white top edge, and a blue shadow down and to the
right. The letters are drawn on a grid of two-pixel cells.

The picture is written as the blitter copies it: for each line, four planes of
LOGO_WORDS words, in the game's fixed palette.
"""

import sys
from pathlib import Path

WORD = "AMIGALAGA"
CELL = 2  # pixels to a cell of a letter's grid
GAP = 2  # pixels between letters
SHADOW = 2  # how far down and right the shadow falls
PLANES = 4
# places in the game's palette (COPPER_PALETTE in tools/make_gfx.py)
WHITE, YELLOW, RUST, BLUE, GOLD = 1, 3, 8, 11, 12
LETTERS = {
    "A": (
        "..######..",
        ".########.",
        "####..####",
        "###....###",
        "###....###",
        "###....###",
        "##########",
        "##########",
        "###....###",
        "###....###",
        "###....###",
        "###....###",
        "###....###",
        "###....###",
    ),
    "M": (
        "###....###",
        "####..####",
        "##########",
        "##########",
        "###.##.###",
        "###.##.###",
        "###....###",
        "###....###",
        "###....###",
        "###....###",
        "###....###",
        "###....###",
        "###....###",
        "###....###",
    ),
    "I": (
        "######",
        "######",
        ".####.",
        "..##..",
        "..##..",
        "..##..",
        "..##..",
        "..##..",
        "..##..",
        "..##..",
        "..##..",
        ".####.",
        "######",
        "######",
    ),
    "G": (
        "..#######.",
        ".#########",
        "####...###",
        "###.......",
        "###.......",
        "###.......",
        "###..#####",
        "###..#####",
        "###....###",
        "###....###",
        "###....###",
        "####..####",
        ".########.",
        "..######..",
    ),
    "L": (
        "###.......",
        "###.......",
        "###.......",
        "###.......",
        "###.......",
        "###.......",
        "###.......",
        "###.......",
        "###.......",
        "###.......",
        "###.......",
        "###.......",
        "##########",
        "##########",
    ),
}


def letters() -> tuple[set[tuple[int, int]], int, int]:
    """The word's pixels as (x, y), and its width and height."""
    pixels, left = set(), 0
    for letter in WORD:
        grid = LETTERS[letter]
        for row, line in enumerate(grid):
            for column, mark in enumerate(line):
                if mark == "#":
                    pixels |= {
                        (left + column * CELL + dx, row * CELL + dy)
                        for dx in range(CELL)
                        for dy in range(CELL)
                    }
        left += len(grid[0]) * CELL + GAP
    return pixels, left - GAP, len(LETTERS["A"]) * CELL


def picture() -> list[list[int]]:
    """The logo as rows of palette places, its width padded to whole words."""
    pixels, width, height = letters()
    words = (width + SHADOW + 15) // 16
    rows = [[0] * (16 * words) for _ in range(height + SHADOW)]
    for x, y in pixels:
        rows[y + SHADOW][x + SHADOW] = BLUE
    for x, y in pixels:
        colour = YELLOW if y < height * 0.45 else GOLD if y < height * 0.7 else RUST
        if (x, y - 1) not in pixels:
            colour = WHITE  # the top edge of every stroke
        rows[y][x] = colour
    return rows


def main() -> None:
    out = Path(sys.argv[1])
    out.mkdir(parents=True, exist_ok=True)
    rows = picture()
    words = len(rows[0]) // 16
    data = bytearray()
    for row in rows:
        for plane in range(PLANES):
            bits = sum(
                1 << (len(row) - 1 - x) for x, c in enumerate(row) if c >> plane & 1
            )
            data += bits.to_bytes(2 * words, "big")
    (out / "logo.bin").write_bytes(data)
    (out / "logo.i").write_text(
        "; generated by tools/make_logo.py - do not edit\n"
        f"LOGO_WORDS\tequ\t{words}\t; words in a plane's line of the logo\n"
        f"LOGO_ROWS\tequ\t{len(rows)}\t; its lines\n"
    )
    print(f"logo {16 * words} x {len(rows)} pixels, {len(data)} bytes")


if __name__ == "__main__":
    main()
