; The FLIGHT_TEST build: fly every test case through the flight stepper and
; report where each one went, for tools/flighttest.py to compare with the
; model the arcade was checked against. Nothing is assembled otherwise.

	include	"config.i"
	include	"hw.i"
	include	"layout.i"
	include	"flight.i"
	include	"sound.i"
	include	"state.i"

	if	FLIGHT_TEST

	xdef	FlightTest
	xref	FlightLaunch
	xref	FlightStep

FRAME_LIMIT	equ	1500			; a flight still going by then is cut off
MAX_CASES	equ	2048
ENV_BYTES	equ	64			; HomeX and HomeLoc

; the report: this header, then one record per case
	rsreset
th_steps	rs.l	1			; FlightStep calls made
th_frames	rs.l	1			; vertical blanks they took
th_SIZEOF	rs.b	0

	rsreset
tr_hash		rs.l	1			; over every frame's position, heading and result
tr_frames	rs.w	1
tr_result	rs.w	1			; what the last FlightStep returned
tr_pos		rs.l	1			; where it ended: y, x
tr_head		rs.l	1
tr_SIZEOF	rs.b	0

	section	code,code

;--
; FlightTest
; Fly every case in TestCases, one at a time, and leave the report for startup to write.
; In:       a5 = state
; Out:      -
; Clobbers: d0-d7, a0-a3
FlightTest:
	move.l	a4,-(sp)
	lea	TestEnv(pc),a0
	lea	HomeX(a5),a1
	moveq	#ENV_BYTES-1,d0
.Env	move.b	(a0)+,(a1)+
	dbra	d0,.Env
	lea	TestCases(pc),a3
	lea	TestLog,a4
	move.l	a4,ReportPtr(a5)
	clr.l	th_steps(a4)
	move.w	FrameCount(a5),d0
	move.l	d0,th_frames(a4)
	addq.l	#th_SIZEOF,a4
.Case	move.w	(a3)+,d0			; script
	bmi	.Done
	moveq	#0,d1
	move.b	(a3)+,d1			; y
	moveq	#0,d2
	move.b	(a3)+,d2			; x
	move.b	(a3)+,d3			; heading
	move.b	(a3)+,d4			; object
	move.b	(a3)+,d5			; mirrored
	move.b	(a3)+,FighterX(a5)
	move.b	(a3)+,StageHard(a5)
	move.b	(a3)+,StageHarder(a5)
	move.b	(a3)+,LastStand(a5)
	move.b	(a3)+,BossKilled(a5)
	lea	Flights(a5),a0
	bsr	FlightLaunch
	clr.w	FlightFrame(a5)
	clr.l	tr_hash(a4)
.Step	bsr	FlightStep
	addq.w	#1,FlightFrame(a5)
	; hash = ((hash rol 5) ^ position) + heading, + offsets in the low word, ^ result
	move.l	tr_hash(a4),d1
	rol.l	#5,d1
	move.l	fl_y(a0),d2
	eor.l	d2,d1
	add.l	fl_head(a0),d1
	add.w	fl_yo(a0),d1
	eor.l	d0,d1
	move.l	d1,tr_hash(a4)
	tst.w	d0
	bne	.Ended
	cmp.w	#FRAME_LIMIT,FlightFrame(a5)
	bne	.Step
.Ended	move.w	FlightFrame(a5),d1
	move.w	d1,tr_frames(a4)
	move.w	d0,tr_result(a4)
	move.l	fl_y(a0),tr_pos(a4)
	move.l	fl_head(a0),tr_head(a4)
	lea	tr_SIZEOF(a4),a4
	move.l	ReportPtr(a5),a1
	ext.l	d1
	add.l	d1,th_steps(a1)
	bra	.Case
.Done	move.l	ReportPtr(a5),a1
	moveq	#0,d0
	move.w	FrameCount(a5),d0
	sub.w	th_frames+2(a1),d0
	move.l	d0,th_frames(a1)
	sub.l	a1,a4
	move.l	a4,ReportLen(a5)
	move.l	(sp)+,a4
	rts

; generated by tools/flighttest.py: TestEnv (the formation at rest) and TestCases
	include	"flight_cases.i"

	section	bss,bss

TestLog:
	ds.b	th_SIZEOF+MAX_CASES*tr_SIZEOF

	endc
