; Stars: the scrolling, fading starfield.
;
; One hardware sprite (sprite 7, a single pixel) is moved and recoloured
; on every raster line by a copper table, so each line can hold one star
; of any colour. The table has no line numbers in it: every entry ends
; with "wait for the end of this line". Scrolling is therefore just
; starting the table at a different entry each frame.
;
; Each star fades between off and full brightness on its own period. The
; fades are a schedule of (colour word, new colour) pairs, a few per
; frame, written into the table here; the schedule loops.
;
; The one thing that needs patching for the scroll: a copper wait cannot
; ignore bit 7 of the line number, so the entries that currently fall on
; raster lines 128-255 carry that bit. Scrolling by n lines moves 2n
; entries across those boundaries.

	include	"config.i"
	include	"hw.i"
	include	"layout.i"
	include	"flight.i"
	include	"sound.i"
	include	"state.i"

	xdef	StarsInit
	xdef	StarsVBlank

STAR_ENTRY	equ	12			; a table entry: move position, move colour, wait
STAR_LINES	equ	256			; lines in the table, which is stored twice over
STAR_COPY	equ	STAR_LINES*STAR_ENTRY	; from an entry to its second copy
STAR_WAIT	equ	8			; offset of an entry's wait: its first byte is the line bits
LINE_BIT7	equ	$80
TO_LINE_128	equ	128-DISPLAY_TOP		; entries from the first line to raster line 128
TO_LINE_256	equ	256-DISPLAY_TOP
FADE_END	equ	-2			; schedule: -1 ends a frame, -2 ends the schedule
COPPER_END	equ	$fffffffe

; Set the line bit of the entry \1 lines below the first one to \2, in both
; copies of the table. d0 = first entry, a1 = table, a2 = its second copy.
SETLINE	macro
	moveq	#0,d1
	move.b	d0,d1
	add.b	#\1,d1
	mulu.w	#STAR_ENTRY,d1
	move.b	#\2,STAR_WAIT(a1,d1.w)
	move.b	#\2,STAR_WAIT(a2,d1.w)
	endm

	section	code,code

;--
; StarsInit
; Start the stars: one line a frame, from the top of the table.
; In:       a5 = state, a6 = CUSTOM
; Out:      -
; Clobbers: -
StarsInit:
	clr.w	StarFirst(a5)
	move.w	#1,StarSpeed(a5)
	move.l	#StarFades,StarFade(a5)
	move.l	#StarTable,cop2lc(a6)
	rts

;--
; StarsVBlank
; Once per frame, from the vertical blank: scroll and fade.
; In:       a5 = state, a6 = CUSTOM
; Out:      -
; Clobbers: d0-d2, a0-a2
StarsVBlank:
	lea	StarTable,a1
	lea	STAR_COPY(a1),a2
	move.w	StarFirst(a5),d0
	move.w	StarSpeed(a5),d2
	beq	.Still
	subq.w	#1,d2
.Step	subq.b	#1,d0				; stars move down: start one entry earlier
	SETLINE	TO_LINE_128,LINE_BIT7		; this entry is now on line 128
	SETLINE	TO_LINE_256,0			; and this one on line 256
	dbf	d2,.Step
	move.w	d0,StarFirst(a5)
.Still	mulu.w	#STAR_ENTRY,d0
	add.l	a1,d0
	move.l	d0,cop2lc(a6)			; the copper jumps here above the display

	move.l	StarFade(a5),a0			; this frame's fade steps
.Fade	move.w	(a0)+,d0			; colour word in the table, negative ends
	bmi	.Faded
	move.w	(a0)+,d1
	move.w	d1,(a1,d0.w)
	move.w	d1,(a2,d0.w)
	bra	.Fade
.Faded	cmp.w	#FADE_END,d0
	bne	.Next
	lea	StarFades,a0
.Next	move.l	a0,StarFade(a5)
	rts

	section	data,data

; generated by tools/make_stars.py: (offset of a colour word, new colour) pairs
StarFades:	incbin	"starev.bin"

	section	chip_data,data_c

; generated by tools/make_stars.py: per line, sprite 7's position and colour, then a wait
StarTable:	incbin	"stars.bin"
	dc.l	COPPER_END
